### ISSUE TITLE
Ansible become method problem

### ISSUE THREAD

**Issue by wiktor2200** [aalaesar/backup_nextcloud#2]
Hi @aalaesar, I experienced some problems with this role. 
At first when I was trying to run `ansible-playbook` command on inventory I got this error just after `Gathering Facts`:
```
TASK [backup_nextcloud : get nextcloud status] ******************************************************************************************************************************************************************************************************************************
fatal: [IP_ADDRESS]: FAILED! => {"msg": "Timeout (12s) waiting for privilege escalation prompt: "}
```
Then after adding `--ask-become-pass` parameter I was still getting on `Gathering Facts`, so in this case it was failing even faster:
```
TASK [Gathering Facts] ******************************************************************************************************************************************************************************************************************************************************
fatal: [IP_ADDRESS]: FAILED! => {"msg": "Missing sudo password"}
```

My playbook was very simple:
```
- hosts: all
  become: true
  vars_files:
    - back_var_file.yml
  roles:
    - role: "backup_nextcloud"
```
and `back_var_file.yml` was just copied and modified `defaults.yml`.

 I guess it's caused by my host configuration (Ubuntu2204, with unprivileged user which require password to get `sudo` command. I think current code could work on `root` while running as root, but I cannot confirm that.

I was finally able to solve this whole issue by removing all `become_method` and `become_flags` parameters across repo.
And it started working.
I'm adding PR right away with changes which fixed this issue.

So I have two questions:
1. Was there any particular reason why you've used:
```
  become_method: su
  become_flags: -s /bin/sh
```
when I removed these lines, default `become_method` was used (`sudo`) and it stared working.
And the second question, 
2. Could you test changes from my PR on your side in your case and if it's working could we merge them? :)

**Comment by aalaesar** [comment]
Hello there ! 😃 

Thank you for your contributions. I'm starting to review them today.

> ```
> TASK [Gathering Facts] ******************************************************************************************************************************************************************************************************************************************************
> fatal: [IP_ADDRESS]: FAILED! => {"msg": "Missing sudo password"}
> ```

I think you were missing the var ansible_become_pass but given your setup that might have not worked either. 😞 

> 1. Was there any particular reason why you've used:
> 
> ```
>   become_method: su
>   become_flags: -s /bin/sh
> ```

Yes: I don't like the hacky way I used in install_nextcloud to run occ command.
Also I made this role with limited tests and use cases so I didn't get this issue (switching to unprivileged user after having acquired privileges) that has [its own section in ansible doc](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html#risks-of-becoming-an-unprivileged-user)

> when I removed these lines, default `become_method` was used (`sudo`) and it stared working. And the second question, 2. Could you test changes from my PR on your side in your case and if it's working could we merge them? :)

I'm pretty sure it won't work without dynamically setting the method if the host uses sudo or not.
but nowadays I'm more obstinate about **not** using set_facts. so a fact dependant jinja expression but be set in vars to reproduce the install role's hack

**Comment by wiktor2200** [comment]
Hi! Thanks for answer. I came up with an idea to solve this problem on both sides. I'll try to set `become_method` and `become_flags` as variable, so anyone could set whatever wanted.

**Comment by wiktor2200** [comment]
I've modified my PR #3, now it's a variable and can be tweaked according to needs.
I've left your values as default and it works for me with this settings:
```yaml
ansible_become_method: "sudo"
ansible_become_flags: ""
```

**Comment by aalaesar** [comment]
That a nice step in the proper direction
However i'd rather have the user not have to do trial and errors regarding setting the proper flags that has to be set accordingly with the method.
this might also affect all tasks that requires simple privileges escalation like to write in the backup folder so setting this flag only for occ tasks is a requirement in my mind. 

but I just found out that I have to deal with my private gitea server syncing on push mode only to this repo. This has reverted merge of #1.
